---
# Cleanup: Remove old fail2ban installation

- name: Remove old fail2ban package (if any)
  ansible.builtin.apt:
    name: "{{ monitoring_packages }}"
    state: absent
    purge: true
  tags:
    - monitoring


- name: Installer Fail2ban pour le monitoring des connexions
  ansible.builtin.apt:
    name: "{{ monitoring_packages }}"
    state: present
  tags:
    - monitoring

- name: Activer et d√©marrer le service Fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - monitoring
