---
# List of development tools to install
# You can edit this list to add/remove packages as needed

docker_packages:
dev_tools_packages:
  - git
  - golang-go
  - nodejs
  - npm
  - python3
  - python3-pip

dev_tools_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
