name: 'Générateur de Clés SSH'

on:
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  create-keys:
    runs-on: ubuntu-latest
    steps:
      - name: '1. Génération de la paire de clés SSH'
        run: ssh-keygen -t rsa -b 4096 -f ./ma_cle_ssh -N ""

      - name: '2. Affichage de la CLÉ PRIVÉE (à mettre dans les secrets GitHub)'
        run: |
          echo "--- COPIEZ TOUT LE BLOC SUIVANT, LIGNES INCLUSES ---"
          cat ./ma_cle_ssh
          echo "--------------------- FIN DU BLOC ---------------------"

      - name: '3. Affichage de la CLÉ PUBLIQUE (à mettre sur le serveur VPS)'
        run: |
          echo "--- COPIEZ LA LIGNE SUIVANTE ---"
          cat ./ma_cle_ssh.pub
          echo "------------- FIN DE LA LIGNE --------------"
          
